#!/usr/bin/env bash

debug="0"
selected=$(find ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z "$selected" ]]; then
	exit 0
fi
selected_name=$(basename $selected | tr ";,. " "____")

while [[ $# -gt 0 ]]; do
	if [[ $1 == "--debug" ]]; then
		debug="1"
	fi
	shift
done

log() {
	if [[ $debug == "1" ]]; then
		echo "[DEBUG]: $@"
	fi
}

switch_to(){
	if [[ -z "$TMUX" ]]; then
		log "attaching session"
		tmux attach-session -t $selected_name
	else
		log "switching client"
		tmux switch-client -t $selected_name
	fi

}

if tmux has-session -t="$selected_name" 2> /dev/null; then
	log "has session \"$selected_name\""
	switch_to
else
	log "has no session \"$selected_name\""
	log "creating session"
	tmux new-session -ds $selected_name -c $selected
	log "sending keys ready-tmux"
	tmux send-keys -t $selected_name "ready-tmux" ^M
	switch_to
fi



