[general]
import = ["~/.config/alacritty/themes/orange-and-teal.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.75
blur = true
option_as_alt = "Both"

[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font"

[terminal]
shell = "zsh"


