preload = ~/.config/nix/dotfiles/wallpapers/oat/autumn-season-leafs-plant-scene-generative-ai.jpg
wallpaper {
    monitor = eDP-1
    path = ~/.config/nix/dotfiles/wallpapers/oat/autumn-season-leafs-plant-scene-generative-ai.jpg
    fit_mode = cover
}

splash = false
ipc = off

