preload = ~/.config/nix/dotfiles/wallpapers/oat/autumn-season-leafs-plant-scene-generative-ai.jpg
wallpaper = ,~/.config/nix/dotfiles/wallpapers/oat/autumn-season-leafs-plant-scene-generative-ai.jpg

splash = false
ipc = off

