# psmux config - mirror of my tmux conf

################################################################################
# BASIC OPTIONS
################################################################################
# set -g mouse on
set -g set-clipboard on
set -g display-time 4000
set -g status-interval 5
set -g history-limit 1000000
set -g escape-time 0

# Start numbering at 1
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Enable extended key reporting to distinguish modified keys (Shift+Enter fix)
set -g extended-keys always # or "on"?

# Advertise extended key support for xterm-compatible terminals
set -as terminal-features 'xterm*:extkeys'

# set -g allow-passthrough on

################################################################################
# COLORS - Orange and Teal
################################################################################
%hidden thm_fg="#f78104"
%hidden thm_bg="#062027"
%hidden thm_teal="#005F60"
%hidden thm_red="#ff4500"
%hidden thm_green="#8ec07c"
%hidden thm_blue="#268bd2"
%hidden thm_magenta="#a277ff"
%hidden thm_cyan="#2aa198"
%hidden thm_white="#a6b2b2"

################################################################################
# KEY BINDINGS
################################################################################
unbind-key C-b
set -g prefix C-t
set -g repeat-time 0
set -g focus-events on

# Split panes with |  - or v  s
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"

# vimlike pane switching
bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# Resizing panes
bind-key -r C-k resize-pane -U 5
bind-key -r C-j resize-pane -D 5
bind-key -r C-h resize-pane -L 5
bind-key -r C-l resize-pane -R 5

# Moving windows
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# kill pane with <prefix> q  (overrides psmux's display-panes on q)
bind-key -r q kill-pane -a

# bind-key o choose-session
# set -g choose-tree-preview on

# floating pane for one-off commands
bind-key f display-popup -E -d "#{pane_current_path}" -w 80% -h 80%
# rebind prefix-f to prefix-F
bind-key F command-prompt "find-window '%%'"

# reload config with <prefix> r
bind-key r source-file ~/.config/psmux/psmux.conf \; display-message "psmux config reloaded!"


################################################################################
# LOOK AND FEEL
################################################################################
# Status bar
set -g status on
set -g status-style "bg=$thm_bg,fg=$thm_fg"
set -g status-justify "left"
set -g status-position "bottom"
set -g status-left " "
set -g status-right " %H:%M %d-%b-%y "
set -g status-left-length 100
set -g status-right-length 100

# Statusline - other windows
set -g window-status-format " #I #W "
set -g window-status-style "fg=$thm_fg,bg=$thm_bg,dim"

# Statusline - current window
set -g window-status-current-format " #I #W "
set -g window-status-current-style "fg=$thm_fg,bg=$thm_bg,bold"

# Messages
set -g message-style "fg=$thm_fg,bg=$thm_bg,align=centre"
set -g message-command-style "fg=$thm_fg,bg=$thm_bg,align=centre"

# Panes
# set -g pane-border-status top
# set -g pane-border-format " "
# set -g pane-border-style "fg=$thm_teal"
# set -g pane-active-border-style "fg=$thm_fg,bold"

set -g popup-border-lines rounded
set -g popup-border-style "fg=$thm_fg"
