# Pomodo plugin settings
set -g @pomodoro_mins 60                                          # The duration of the Pomodoro
set -g @pomodoro_break_mins 10                                    # The duration of the break after the Pomodoro completes
set -g @pomodoro_intervals 6                                      # The number of intervals before a longer break is started
set -g @pomodoro_long_break_mins 45                               # The duration of the long break
set -g @pomodoro_repeat 'on'                                      # Automatically repeat the Pomodoros?
set -g @pomodoro_on "󱎫 "
set -g @pomodoro_complete "#[fg=#8fc66b]󱎫  "                # The formatted output when the break is running
set -g @pomodoro_pause "#[fg=#e8b654]󱎫  "                   # The formatted output when the Pomodoro/break is paused
set -g @pomodoro_prompt_break " ⏲︎ break?"                        # The formatted output when waiting to start a break
set -g @pomodoro_prompt_pomodoro " ⏱︎ start?"                     # The formatted output when waiting to start a Pomodoro
set -g @pomodoro_interval_display " [%s/%s]"
set -g @pomodoro_granularity 'on'
set -g status-interval 1

set -g status-right "#{pomodoro_status}#{pomodoro_show_intervals}    #[fg=yellow] %H:%M "
set -g status-right-style "fg=yellow"

set -g @plugin 'olimorris/tmux-pomodoro-plus'
