set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm*:Tc"

################################################################################
# KEY BINDINGS
################################################################################
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0
set-option -g focus-events on

# Split panes with |  - or v  s
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# vimlike pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Resizing panes
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# Moving windows
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Copy to system clipboard using xclip
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# kill pane with <prefix> q
bind -r q kill-pane -a

# reload tmux config with <prefix> r
bind r source-file ~/.config/tmux/tmux.conf; display "TMUX config reloaded!"

################################################################################
# BASIC OPTIONS
################################################################################
set -g mouse on
set -g set-clipboard on
set -g display-time 4000
set -g status-interval 5
#set-option utf8-default on
#set-window-option -g utf8 on
set-window-option -g mode-keys vi
set-option -g renumber-windows on
set-option -g history-limit 1000000
set-option -g base-index 1
set -sg escape-time 0


################################################################################
# LOOK AND FEEL
################################################################################
# set-option -g status 2
set-option -g status-justify "left"
set-option -g status-position "bottom"
# set-option -g status-right ""
set-option -g status-bg "#005F60"
set-option -g status-left " "
set-option -g window-status-format " #I " # add #W for name
set-option -g window-status-style "fg=color130"

set-option -g window-status-current-format "[#I]"
set-option -g window-status-current-style fg=yellow

set-option -g message-style bg=#23272E,fg=yellow

set -g pane-active-border-style fg=yellow,bg=default
set -g window-style fg=white,bg=default
set -g window-active-style fg=white,bg=default

# default colors
#set-option -g status-style bg=yellow,fg=black
#set-window-option -g window-status-style fg=yellow,bg=default,dim
#set-window-option -g window-status-current-style fg=yellow,bg=default,bright

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'sainnhe/tmux-fzf'
#source-file ./pomo.conf

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
